export const EXAMPLE_EXERCISES = [
  {
    focus: 'Full Body',
    id: 'rec07btBNS0Cl9FGq',
    level: 'Intermediate',
    name: 'Cross Body Snatch',
  },
  {
    focus: 'Legs',
    id: 'rec2sqKBpLELAEGoN',
    level: 'Intermediate',
    name: 'Jump Swing',
  },
  {
    focus: 'Full Body',
    id: 'rec4IEjBf0ydvJGU2',
    level: 'Beginner',
    name: 'Upright Pull',
  },
  {
    focus: 'Core',
    id: 'rec4ViETT7LHJ7zDS',
    level: 'Advanced',
    name: 'High Windmill',
  },
  {
    focus: 'Cardio',
    id: 'rec4aynpqDWEo7Tyv',
    level: 'Intermediate',
    name: 'Snatch Side Swing',
  },
  {
    focus: 'Arms',
    id: 'rec4sRF0ya9ZJV5X7',
    level: 'Intermediate',
    name: 'Overhead "C"',
  },
  {
    focus: 'Cardio',
    id: 'rec5MVBFSN2zBUypR',
    level: 'Advanced',
    name: 'Speed Skater Clean',
  },
  {
    focus: 'Legs',
    id: 'rec5svjokc7BFRomz',
    level: 'Beginner',
    name: 'Suitcase Deadlift',
  },
  {
    focus: 'Legs',
    id: 'rec5z9JbPY7qGpnqk',
    level: 'Beginner',
    name: 'Step Swing',
  },
  {
    focus: 'Full Body',
    id: 'rec5zRBeEejGaWUBx',
    level: 'Advanced',
    name: '1 Arm Clean Thruster',
  },
  {
    focus: 'Legs',
    id: 'rec67qu7XDtjCs5zP',
    level: 'Intermediate',
    name: 'Up Down Lunge',
  },
  {
    focus: 'Cardio',
    id: 'rec6Azf7ka9njdvit',
    level: 'Intermediate',
    name: 'Side Skip Swing',
  },
  {
    focus: 'Core',
    id: 'rec9Xrr8mxdc3dU4t',
    level: 'Intermediate',
    name: 'Seated Figure 8',
  },
  {
    focus: 'Legs',
    id: 'rec9dq1Lqw5e8xJdD',
    level: 'Beginner',
    name: 'Deadlift',
  },
  {
    focus: 'Legs',
    id: 'recBOjTKJtEZ5OR6l',
    level: 'Beginner',
    name: 'Goblet Squat',
  },
  {
    focus: 'Full Body',
    id: 'recBRPraZllSMmNJq',
    level: 'Intermediate',
    name: 'Lateral Lunge Clean Press',
  },
  {
    focus: 'Full Body',
    id: 'recBrd4UouoRr3RWH',
    level: 'Intermediate',
    name: 'Clean',
  },
  {
    focus: 'Cardio',
    id: 'recC5WCV2ItBrxcSA',
    level: 'Advanced',
    name: 'Alternating 180 Swing',
  },
  {
    focus: 'Core',
    id: 'recCGRXvSDPY7djBh',
    level: 'Beginner',
    name: 'Seated Oblique Swing',
  },
  {
    focus: 'Legs',
    id: 'recCu7hxgOhpwZXDu',
    level: 'Intermediate',
    name: 'Lateral Jump Swing',
  },
  {
    focus: 'Cardio',
    id: 'recD5UbhC7mErm3Pb',
    level: 'Beginner',
    name: 'American Swing',
  },
  {
    focus: 'Arms',
    id: 'recDQcHKlBTuNwR3M',
    level: 'Intermediate',
    name: 'Lying Tricep Extension',
  },
  {
    focus: 'Core',
    id: 'recDSTyJH1iXWuDB8',
    level: 'Intermediate',
    name: 'Low Windmill',
  },
  {
    focus: 'Cardio',
    id: 'recDbc4kQCcpx1cD1',
    level: 'Intermediate',
    name: 'Fast Feet Swing',
  },
  {
    focus: 'Arms',
    id: 'recDrlnaDVQkIdTsF',
    level: 'Intermediate',
    name: 'Hammer Curl',
  },
  {
    focus: 'Core',
    id: 'recEHaBgCWKVKNPnd',
    level: 'Advanced',
    name: 'Jackknife',
  },
  {
    focus: 'Cardio',
    id: 'recEZgybXnUBO12Ms',
    level: 'Beginner',
    name: '1 Arm Swing',
  },
  {
    focus: 'Legs',
    id: 'recFKK7e7oXs0TTRn',
    level: 'Intermediate',
    name: 'Good Morning',
  },
  {
    focus: 'Core',
    id: 'recFNngnvJNHUENLH',
    level: 'Beginner',
    name: 'Standing Side Bend',
  },
  {
    focus: 'Shoulders',
    id: 'recGzF5Sr5cv8yzVq',
    level: 'Intermediate',
    name: '2 Hand Push Press',
  },
  {
    focus: 'Legs',
    id: 'recHATccYERQlRHFt',
    level: 'Beginner',
    name: 'Figure 8 Squat',
  },
  {
    focus: 'Chest',
    id: 'recHVDniBkX4KYbjP',
    level: 'Intermediate',
    name: 'Staggered Push Up',
  },
  {
    focus: 'Legs',
    id: 'recHYQsJglIyrdxgY',
    level: 'Advanced',
    name: '1 Leg Deadlift',
  },
  {
    focus: 'Legs',
    id: 'recIOqVRy0GxmLvVM',
    level: 'Beginner',
    name: 'Rack Squat',
  },
  {
    focus: 'Chest',
    id: 'recIjPkDHUgsHHFsk',
    level: 'Beginner',
    name: 'Bell Touch Push Up',
  },
  {
    focus: 'Full Body',
    id: 'recJAFFhPuiAbjK03',
    level: 'Intermediate',
    name: 'Clean Press',
  },
  {
    focus: 'Shoulders',
    id: 'recKGej5OU35BqMa0',
    level: 'Advanced',
    name: 'Bottom Up Press',
  },
  {
    focus: 'Cardio',
    id: 'recKiYKbyiQ384d0O',
    level: 'Intermediate',
    name: 'Switch Swing',
  },
  {
    focus: 'Arms',
    id: 'recLGaPus8IgXUGZs',
    level: 'Intermediate',
    name: 'Over the Shoulder',
  },
  {
    focus: 'Cardio',
    id: 'recMJVlyVj7TM7i4x',
    level: 'Beginner',
    name: 'High Pull',
  },
  {
    focus: 'Chest',
    id: 'recMe0o76KRf7MwBs',
    level: 'Advanced',
    name: '1 Arm Push Up',
  },
  {
    focus: 'Full Body',
    id: 'recPDnqFyVp8KXW4g',
    level: 'Beginner',
    name: 'Rack Thruster',
  },
  {
    focus: 'Chest',
    id: 'recQmYJxkArTIJibH',
    level: 'Beginner',
    name: 'Handle Push Up',
  },
  {
    focus: 'Arms',
    id: 'recRAekP0Yow1iUja',
    level: 'Beginner',
    name: '1 Arm Tricep Extension',
  },
  {
    focus: 'Shoulders',
    id: 'recRv5O0GqSbpiugH',
    level: 'Beginner',
    name: '2 Hand Press',
  },
  {
    focus: 'Legs',
    id: 'recS2aLC9T03RMTec',
    level: 'Advanced',
    name: 'Pistol Squat',
  },
  {
    focus: 'Full Body',
    id: 'recS4xkjEfG6G2oWc',
    level: 'Advanced',
    name: 'Bottom Up Thruster',
  },
  {
    focus: 'Full Body',
    id: 'recSLnJnIzZCUssSK',
    level: 'Beginner',
    name: 'Goblet Squat Knee Strike',
  },
  {
    focus: 'Core',
    id: 'recSWYKMcsMxzf0yO',
    level: 'Beginner',
    name: 'Overhead Situp',
  },
  {
    focus: 'Full Body',
    id: 'recU4DTgSgvnzPxJd',
    level: 'Beginner',
    name: 'Goblet Thruster',
  },
  {
    focus: 'Full Body',
    id: 'recVKwhFACZUkb0le',
    level: 'Intermediate',
    name: 'Snatch',
  },
  {
    focus: 'Full Body',
    id: 'recW1T2wNDuK3o2qB',
    level: 'Advanced',
    name: '2 Hand Clean Thruster',
  },
  {
    focus: 'Chest',
    id: 'recW3U2TlOCKItrUY',
    level: 'Beginner',
    name: '1 Arm Floor Press',
  },
  {
    focus: 'Cardio',
    id: 'recWh0R3baFN3REQT',
    level: 'Beginner',
    name: '180 Swing',
  },
  {
    focus: 'Full Body',
    id: 'recWzIF6OpuEiKDpO',
    level: 'Advanced',
    name: 'Turkish Get Up',
  },
  {
    focus: 'Legs',
    id: 'recX7zyAsf2y47i4u',
    level: 'Advanced',
    name: 'Overhead Lunge Back',
  },
  {
    focus: 'Cardio',
    id: 'recXQmftHJ58tgwls',
    level: 'Beginner',
    name: 'Around the Body Cross Swing',
  },
  {
    focus: 'Cardio',
    id: 'recZqU8aUb2cL5WMS',
    level: 'Advanced',
    name: 'Lunge Pass Under',
  },
  {
    focus: 'Chest',
    id: 'recZss7E9DwnP3r1p',
    level: 'Advanced',
    name: 'Bottom Up Push Up',
  },
  {
    focus: 'Legs',
    id: 'recamRPsQh0UMTGkp',
    level: 'Intermediate',
    name: 'Jump Back Swing',
  },
  {
    focus: 'Core',
    id: 'recbCy7M87unTSaTt',
    level: 'Beginner',
    name: 'Oblique Hip Raise',
  },
  {
    focus: 'Shoulders',
    id: 'recbnh1vEnosDjGq0',
    level: 'Advanced',
    name: 'Rack Push Press',
  },
  {
    focus: 'Shoulders',
    id: 'recc8qwPSKPo6WOlI',
    level: 'Intermediate',
    name: 'Rack Press',
  },
  {
    focus: 'Shoulders',
    id: 'reccaAlUDkkwNkro1',
    level: 'Beginner',
    name: 'Halo',
  },
  {
    focus: 'Cardio',
    id: 'recd0vAHuTbtN9uc2',
    level: 'Advanced',
    name: 'Swing Front Back Jump',
  },
  {
    focus: 'Chest',
    id: 'recdy40HlZe9ezyUy',
    level: 'Intermediate',
    name: 'Alternating Plyo Push Up',
  },
  {
    focus: 'Legs',
    id: 'recdyuVn8KTQCSNGP',
    level: 'Beginner',
    name: 'Lunge Pass Under',
  },
  {
    focus: 'Full Body',
    id: 'recdzEQsVBv02G1zP',
    level: 'Beginner',
    name: 'Sidewinder',
  },
  {
    focus: 'Arms',
    id: 'receQWmIv3rCcmnor',
    level: 'Beginner',
    name: 'Front Circle',
  },
  {
    focus: 'Shoulders',
    id: 'recemRlaogl0LTIXT',
    level: 'Beginner',
    name: 'Front Raise',
  },
  {
    focus: 'Full Body',
    id: 'recew09u4qkWmgY4p',
    level: 'Intermediate',
    name: 'Clean & Jerk',
  },
  {
    focus: 'Cardio',
    id: 'recg127wjO34gBLr6',
    level: 'Advanced',
    name: 'Back Walking 1 Arm Swing',
  },
  {
    focus: 'Legs',
    id: 'recgNaboJNQVfUWqe',
    level: 'Intermediate',
    name: 'Lateral Goblet Squat',
  },
  {
    focus: 'Back',
    id: 'recglj0Nxk8e4fCcv',
    level: 'Advanced',
    name: '1 Leg Row',
  },
  {
    focus: 'Back',
    id: 'rech3IYMkVIEDHewj',
    level: 'Intermediate',
    name: 'Pull Over',
  },
  {
    focus: 'Core',
    id: 'rechWOaTLSxlRpstf',
    level: 'Intermediate',
    name: 'Russian Twist',
  },
  {
    focus: 'Arms',
    id: 'reciQ4C0TSAUW8J2f',
    level: 'Advanced',
    name: 'Goblet Squat Concentration Curl',
  },
  {
    focus: 'Chest',
    id: 'reciexjCfnRmfjd9h',
    level: 'Advanced',
    name: 'Bottom Up Pushup Horizontal',
  },
  {
    focus: 'Core',
    id: 'recj5qYc9O3ENiaYy',
    level: 'Beginner',
    name: 'Knees to Chest',
  },
  {
    focus: 'Full Body',
    id: 'recktpvTsquUOEDlc',
    level: 'Beginner',
    name: 'Press Situp Twist',
  },
  {
    focus: 'Full Body',
    id: 'recldRBQQ2KW6Nh07',
    level: 'Intermediate',
    name: 'Situp Press',
  },
  {
    focus: 'Cardio',
    id: 'reclyLc8TyXOCWRRh',
    level: 'Intermediate',
    name: 'Side Step Alternating Swing',
  },
  {
    focus: 'Legs',
    id: 'recmBTRBTesteaWKD',
    level: 'Intermediate',
    name: 'Calf Raise Swing',
  },
  {
    focus: 'Arms',
    id: 'recmKWklyRk3IY2WS',
    level: 'Beginner',
    name: 'Goblet Curl',
  },
  {
    focus: 'Core',
    id: 'recoXuxqoNai3EN2j',
    level: 'Advanced',
    name: 'Bottom Up Plank Hold',
  },
  {
    focus: 'Back',
    id: 'recoe7dFNLge4uhHc',
    level: 'Intermediate',
    name: 'Alternating Plank Row',
  },
  {
    focus: 'Arms',
    id: 'recoyCWalCf4GjQJH',
    level: 'Beginner',
    name: 'Shoulder Toss',
  },
  {
    focus: 'Cardio',
    id: 'recpEITQrkmZ5IKcL',
    level: 'Beginner',
    name: 'Swing',
  },
  {
    focus: 'Full Body',
    id: 'recqKoia3bM1hrHUe',
    level: 'Intermediate',
    name: 'Lunge Press',
  },
  { focus: 'Back', id: 'recr3iNZNIpHKyBOl', level: 'Beginner', name: 'Row' },
  {
    focus: 'Legs',
    id: 'rectg8QSctm5vYAio',
    level: 'Beginner',
    name: 'Rack Lateral Lunge',
  },
  {
    focus: 'Cardio',
    id: 'recuJ0eKHJ5rwyqBi',
    level: 'Beginner',
    name: 'Alternating 1 Arm Swing',
  },
  {
    focus: 'Legs',
    id: 'recuc7zs8gEpbVtMV',
    level: 'Intermediate',
    name: 'Clock Lunge Clean',
  },
  {
    focus: 'Full Body',
    id: 'recuwFxfG8ItShOFr',
    level: 'Beginner',
    name: 'Vertical Pull',
  },
  {
    focus: 'Full Body',
    id: 'recw07yjRdK87cfi7',
    level: 'Advanced',
    name: 'Bottom Up Clean Press',
  },
  {
    focus: 'Core',
    id: 'recwN5PF8lMO4FBV1',
    level: 'Intermediate',
    name: 'Alternating Toe Touch',
  },
  {
    focus: 'Core',
    id: 'recwcVdvg5btTBD5z',
    level: 'Beginner',
    name: 'Around the Body Swing',
  },
  {
    focus: 'Core',
    id: 'recweVusjdLTh2eVH',
    level: 'Intermediate',
    name: 'Clam Shell',
  },
  {
    focus: 'Arms',
    id: 'recxSbZiyJ90v3SJq',
    level: 'Beginner',
    name: '2 Hand Tricep Extension',
  },
  {
    focus: 'Full Body',
    id: 'recy0ZT7Bej13je3q',
    level: 'Beginner',
    name: 'Ribbons',
  },
  {
    focus: 'Cardio',
    id: 'recy2FSRWXp6lbHDx',
    level: 'Intermediate',
    name: 'Walking 1 Arm Swing',
  },
  {
    focus: 'Core',
    id: 'recyMlxTdG7GOkNEu',
    level: 'Beginner',
    name: 'Cross Swing',
  },
  {
    focus: 'Core',
    id: 'recyRxIyiC4eU6a4m',
    level: 'Advanced',
    name: 'Get Up Situp',
  },
  {
    focus: 'Core',
    id: 'reczpvcmQE4l7TPFf',
    level: 'Intermediate',
    name: 'Haymaker Situp',
  },
  {
    focus: 'Cardio',
    id: 'recztT4pb0AKg4YbZ',
    level: 'Advanced',
    name: 'Skip Swing',
  },
];
